services:
  dvwa-sql-db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: dvwa
    volumes:
      - db_data:/var/lib/mysql

  dvwa-vulnerable:
    image: vulnerables/web-dvwa
    depends_on:
      - dvwa-sql-db
    ports:
      - "8080:80"
    environment:
      - DB_SERVER=db
      - DB_DATABASE=dvwa
      - DB_USER=dvwa
      - DB_PASSWORD=dvwa
    restart: unless-stopped

volumes:
  db_data: